// Scripted Pipeline
node {
    // mengunduh Docker image bernama node:16-buster-slim dan menjalankan image sebagai container terpisah
    def dockerImg = docker.image('node:lts-buster-slim')
    
    // membuat Node container dapat diakses sementara melalui port 3000
    dockerImg.inside('-p 3000:3000') {
        env.CI = 'true' // set environment CI

        // mendefinisikan sebuah tahapan yang disebut Build yang muncul di Jenkins UI
        stage('Build') { 
            sh 'npm install' // mengeksekusi perintah npm untuk memastikan bahwa semua dependencies yang diperlukan untuk menjalankan React App telah diunduh ke direktori node_modules
        }

        // mendefinisikan stage yang disebut Test yang muncul di Jenkins UI
        stage('Test') {
            sh './jenkins/scripts/test.sh' // menjalankan shell script bernama test.sh yang berlokasi di direktori jenkins/scripts dari root pada react-app repository
        }

        // mendefinisikan stage yang disebut Deploy yang muncul di Jenkins UI
        stage('Deploy') {
            sh './jenkins/scripts/deliver.sh' // menjalankan shell script bernama deliver.sh yang berlokasi di direktori jenkins/scripts dari root pada react-app repository

            input message: 'Sudah selesai menggunakan React App? (klik "proceed" untuk mengakhiri)' // untuk mengakhiri dijalankannya aplikasi dan lanjut untuk proses selanjutnya 
                
            sh './jenkins/scripts/kill.sh' // script yg bertugas untuk mengakhiri proses npm dari script deliver.sh sebelumnya
        }
    } // end of dockerImg
}
